# Generated by Django 5.2.17 on 2026-09-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=20)),
                ('touch_type', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('weight', models.FloatField(default=1.0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='leads.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('occurred_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('hypothesis', models.TextField()),
                ('channel', models.CharField(max_length=20)),
                ('variable', models.CharField(max_length=80)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('primary_metric', models.CharField(default='conversion_rate', max_length=60)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('running', 'Running'), ('concluded', 'Concluded'), ('abandoned', 'Abandoned')], default='proposed', max_length=12)),
                ('confidence', models.FloatField(default=0)),
                ('winner', models.CharField(blank=True, max_length=40)),
                ('lift_pct', models.FloatField(default=0)),
                ('learning', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('owner_agent', models.CharField(blank=True, max_length=60)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('confidence', models.FloatField(default=0.8)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('applies_to', models.JSONField(blank=True, default=list)),
                ('times_applied', models.PositiveIntegerField(default=0)),
                ('impact_score', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('source_experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.experiment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('kind', models.CharField(choices=[('new', 'New'), ('expansion', 'Expansion'), ('renewal', 'Renewal')], default='new', max_length=12)),
                ('source_channel', models.CharField(blank=True, max_length=20)),
                ('closing_channel', models.CharField(blank=True, max_length=20)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField()),
                ('days_to_close', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events', to='leads.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-closed_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=20)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('mqls', models.PositiveIntegerField(default=0)),
                ('sqls', models.PositiveIntegerField(default=0)),
                ('meetings', models.PositiveIntegerField(default=0)),
                ('opportunities', models.PositiveIntegerField(default=0)),
                ('customers', models.PositiveIntegerField(default=0)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
                'unique_together': {('workspace', 'date', 'channel')},
            },
        ),
    ]
