# Generated by Django 5.2.17 on 2026-09-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(default='Confident, precise, outcome-led. No hype.', max_length=200)),
                ('voice_rules', models.JSONField(blank=True, default=list)),
                ('vocabulary_preferred', models.JSONField(blank=True, default=list)),
                ('vocabulary_banned', models.JSONField(blank=True, default=list)),
                ('primary_color', models.CharField(default='#6d5dfc', max_length=9)),
                ('secondary_color', models.CharField(default='#22d3ee', max_length=9)),
                ('font_family', models.CharField(default='Inter', max_length=80)),
                ('approved_claims', models.JSONField(blank=True, default=list)),
                ('forbidden_claims', models.JSONField(blank=True, default=list)),
                ('legal_disclaimer', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('founder_brief', models.TextField(blank=True, help_text='Natural-language objective from the founder')),
                ('currency', models.CharField(default='INR', max_length=6)),
                ('revenue_goal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('marketing_budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gross_margin_pct', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('target_geographies', models.JSONField(blank=True, default=list)),
                ('business_model', models.CharField(default='b2b_saas', max_length=40)),
                ('average_deal_size', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sales_cycle_days', models.PositiveIntegerField(default=60)),
                ('derived_plan', models.JSONField(blank=True, default=dict, help_text='AI CMO derivation: segments, personas, channels...')),
                ('plan_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('copilot', 'Copilot - AI recommends, human executes'), ('autonomous_with_approval', 'Autonomous with approval'), ('full_autonomy', 'Full autonomy within limits')], default='autonomous_with_approval', max_length=40)),
                ('daily_spend_cap', models.DecimalField(decimal_places=2, default=200000.0, max_digits=14)),
                ('monthly_spend_cap', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_daily_outbound', models.PositiveIntegerField(default=500)),
                ('can_change_pricing', models.BooleanField(default=False)),
                ('can_email_unapproved_icps', models.BooleanField(default=False)),
                ('can_launch_paid_without_approval', models.BooleanField(default=False)),
                ('can_publish_social_without_approval', models.BooleanField(default=False)),
                ('compliance_gate_required', models.BooleanField(default=True)),
                ('regulated_vertical', models.BooleanField(default=False)),
                ('agent_mode_overrides', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='accounts.workspace')),
            ],
        ),
    ]
