# Generated by Django 5.2.17 on 2026-09-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('website', models.URLField(blank=True)),
                ('positioning', models.TextField(blank=True)),
                ('target_customer', models.CharField(blank=True, max_length=200)),
                ('pricing', models.CharField(blank=True, max_length=200)),
                ('usps', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('ad_messages', models.JSONField(blank=True, default=list, help_text='Observed ad creative / messaging patterns')),
                ('seo_keywords', models.JSONField(blank=True, default=list)),
                ('funding', models.CharField(blank=True, max_length=120)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('share_of_voice', models.FloatField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('product', 'Product'), ('customer', 'Customer'), ('problem', 'Problem'), ('solution', 'Solution'), ('differentiator', 'Differentiator'), ('pricing', 'Pricing'), ('sales_cycle', 'Sales Cycle'), ('geography', 'Geography'), ('objection', 'Objection'), ('use_case', 'Use Case'), ('outcome', 'Outcome'), ('persona', 'Persona')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0.8)),
                ('freshness', models.DateField(blank=True, null=True)),
                ('related', models.ManyToManyField(blank=True, to='knowledge.knowledgeentity')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('news', 'News'), ('funding', 'Funding'), ('hiring', 'Hiring'), ('launch', 'Launch'), ('pricing', 'Pricing'), ('regulatory', 'Regulatory'), ('trend', 'Trend'), ('competitor', 'Competitor'), ('complaint', 'Complaint')], max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('entity', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('sentiment', models.CharField(default='neutral', max_length=12)),
                ('relevance', models.FloatField(default=0.5)),
                ('opportunity', models.BooleanField(default=False)),
                ('actioned', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
