# Generated by Django 5.2.17 on 2026-09-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('replied', 'Replied'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=14)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('personalization', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leads.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('persona', models.CharField(blank=True, max_length=80)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('linkedin', 'Linkedin'), ('multi', 'Multi')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('daily_cap', models.PositiveIntegerField(default=150)),
                ('compliance_status', models.CharField(default='pending', max_length=20)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('replied', models.PositiveIntegerField(default=0)),
                ('positive_replies', models.PositiveIntegerField(default=0)),
                ('meetings', models.PositiveIntegerField(default=0)),
                ('bounced', models.PositiveIntegerField(default=0)),
                ('icp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='leads.icp')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('classification', models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_now', 'Not Now'), ('wrong_person', 'Wrong Person'), ('send_info', 'Send Info'), ('pricing_request', 'Pricing'), ('meeting_request', 'Meeting'), ('objection', 'Objection'), ('unsubscribe', 'Unsubscribe'), ('negative', 'Negative'), ('out_of_office', 'Ooo')], max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('sdr_response', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('meeting_booked_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='leads.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='outbound.sequence')),
            ],
            options={
                'verbose_name_plural': 'replies',
                'ordering': ('-received_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('channel', models.CharField(default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('personalization_hooks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('qa_passed', 'Qa Passed'), ('qa_flagged', 'Qa Flagged'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('bounced', 'Bounced')], default='drafted', max_length=12)),
                ('qa', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='leads.contact')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='outbound.enrollment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='outbound.sequence')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='outbound.sequence'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('sequence', 'contact')},
        ),
    ]
