# Generated by Django 5.2.17 on 2026-09-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=160)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('funding_stage', models.CharField(blank=True, max_length=60)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('fit_score', models.PositiveSmallIntegerField(default=0)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=3)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('enriched', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True)),
                ('logo_seed', models.CharField(blank=True, max_length=60)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ('-fit_score', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('seniority', models.CharField(blank=True, max_length=40)),
                ('persona', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_status', models.CharField(choices=[('unverified', 'Unverified'), ('valid', 'Valid'), ('risky', 'Risky'), ('invalid', 'Invalid')], default='unverified', max_length=12)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('stage', models.CharField(choices=[('unknown', 'Unknown'), ('visitor', 'Visitor'), ('lead', 'Lead'), ('mql', 'Mql'), ('sql', 'Sql'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('repeat', 'Repeat'), ('advocate', 'Advocate')], default='lead', max_length=14)),
                ('lead_score', models.PositiveSmallIntegerField(default=0)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('intelligence_card', models.JSONField(blank=True, default=dict, help_text='Prospect Intelligence Card (spec 2.8)')),
                ('enrichment_log', models.JSONField(blank=True, default=list, help_text='Waterfall provider attempts')),
                ('verification', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('owner', models.CharField(blank=True, max_length=80)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.company')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paused', 'Paused')], default='draft', max_length=12)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('personas', models.JSONField(blank=True, default=list)),
                ('buying_signals', models.JSONField(blank=True, default=list)),
                ('expected_acv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_tam', models.PositiveIntegerField(default=0)),
                ('fit_summary', models.TextField(blank=True)),
                ('prospects_count', models.PositiveIntegerField(default=0)),
                ('reply_rate', models.FloatField(default=0)),
                ('meeting_rate', models.FloatField(default=0)),
                ('cac', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('rank', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='icp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='leads.icp'),
        ),
    ]
