# Generated by Django 5.2.17 on 2026-09-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('simulated', 'Simulated'), ('error', 'Error')], default='not_connected', max_length=20)),
                ('account_label', models.CharField(blank=True, max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('_credentials', models.TextField(blank=True, db_column='credentials')),
                ('health', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ('provider',),
                'abstract': False,
                'unique_together': {('workspace', 'provider')},
            },
        ),
    ]
